site: Jan's Blog
url: https://janschill.de
title: Jan's Blog
description: My personal blog about technology and life
twitter:
  username: janschill
  card: summary
  creator: janschill
author:
  twitter: janschill
  name: Jan Schill
  avatar:
  email: blog@janschill.de
  url: https://janschill.de
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
